SELECT WO.WONUM,
COALESCE(MA.ASSETNUM,WO.ASSETNUM) AS ASSETNUM,
WO.REPORTDATE,
WO.DESCRIPTION,
WO.WORKTYPE,
WO.STATUS
FROM MAXIMO.WORKORDER WO
LEFT JOIN MAXIMO.MULTIASSETLOCCI MA ON MA.SITEID = WO.SITEID AND MA.RECORDKEY = WO.WONUM
WHERE WO.SITEID = 'HMA'
	AND (WO.ASSETNUM IN ('?') OR MA.ASSETNUM IN ('?'))
	AND WO.REPORTDATE BETWEEN DATE('?') AND DATE('?')
	AND WO.ISTASK = 0