SELECT DISTINCT
    WO.WONUM,
    WO.ASSETNUM AS ASSETNUM,
    WO.REPORTDATE,
    WO.DESCRIPTION,
    WO.WORKTYPE,
    WO.STATUS
FROM {{maximo_schema}}.WORKORDER WO
WHERE WO.SITEID = ?
  AND WO.ASSETNUM IN ({{asset_placeholders}})
  AND WO.REPORTDATE >= ?
  AND WO.REPORTDATE < ?
  AND WO.ISTASK = 0

UNION

SELECT DISTINCT
    WO.WONUM,
    MA.ASSETNUM AS ASSETNUM,
    WO.REPORTDATE,
    WO.DESCRIPTION,
    WO.WORKTYPE,
    WO.STATUS
FROM {{maximo_schema}}.WORKORDER WO
JOIN {{maximo_schema}}.MULTIASSETLOCCI MA
  ON MA.SITEID = WO.SITEID
 AND MA.RECORDKEY = WO.WONUM
WHERE WO.SITEID = ?
  AND MA.ASSETNUM IN ({{asset_placeholders}})
  AND WO.REPORTDATE >= ?
  AND WO.REPORTDATE < ?
  AND WO.ISTASK = 0

ORDER BY REPORTDATE DESC, WONUM DESC
